PLCG/Controllers/CompanyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations.Model;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PLCG.Models;
using PLCG.Concrete;

namespace PLCG.Controllers
{
    public class CompanyController : Controller
    {
        private EFDbContext _efDbContext = new EFDbContext();

        #region Read

        public ActionResult Index()
        {
            return View(_efDbContext.Companies);
        }

        #endregion

        #region Delete

        public RedirectToRouteResult Delete(Company company, string returnUrl)
        {
            Company comp = _efDbContext.Companies.FirstOrDefault(c => c.CompanyID == company.CompanyID);

            if (comp != null)
            {
                _efDbContext.Companies.Remove(comp);
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Create

        public ViewResult Create()
        {
            return View(new Company());
        }

        [HttpPost]
        public ActionResult Create(Company company, string returnUrl)
        {
            Company comp = new Company
            {
                CompanyName = company.CompanyName,
                CompanyAddress = company.CompanyAddress
            };

            _efDbContext.Companies.Add(comp);
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Update

        public ActionResult Update()
        {
            return View(new Company());
        }

        [HttpPost]
        public ActionResult Update(Company company, string returnUrl)
        {
            Company comp = _efDbContext.Companies.FirstOrDefault(c => c.CompanyID == company.CompanyID);

            if (comp != null)
            {
                comp.CompanyName = company.CompanyName;
                comp.CompanyAddress = company.CompanyAddress;
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion
    }
}

PLCG/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PLCG.Models;
using PLCG.Concrete;
using System.Data.Entity;
using System.Reflection;

namespace PLCG.Controllers
{
    public class LocationController : Controller
    {
        private EFDbContext _efDbContext = new EFDbContext();

        #region Read

        public ActionResult Index()
        {
            return View(_efDbContext.Locations);
        }

        #endregion

        #region Delete

        public RedirectToRouteResult Delete(Location location, string returnUrl)
        {
            Location loc = _efDbContext.Locations.FirstOrDefault(l => l.LocationID == location.LocationID);
            if (loc != null)
            {
                _efDbContext.Locations.Remove(loc);
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Create

        public ViewResult Create()
        {
            return View(new Location());
        }

        [HttpPost]
        public ActionResult Create(Location location, string returnUrl)
        {
            Location loc = new Location
            {
                LocationCity = location.LocationCity,
                LocationCountry = location.LocationCountry,
                LocationState = location.LocationState,
                LocationZip = location.LocationZip,
                LocationRadius = location.LocationRadius
            };

            _efDbContext.Locations.Add(loc);
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Update

        public ActionResult Update()
        {
            return View(new Location());
        }

        public ActionResult Update(Location location, string returnUrl)
        {
            Location loc = _efDbContext.Locations.FirstOrDefault(l => l.LocationID == location.LocationID);

            if (loc != null)
            {
                loc.LocationCity = location.LocationCity;
                loc.LocationZip = location.LocationZip;
                loc.LocationState = location.LocationState;
                loc.LocationCountry = location.LocationCountry;
                loc.LocationRadius = location.LocationRadius;
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion
    }
}

PLCG/Controllers/TechnologyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PLCG.Models;
using PLCG.Concrete;

namespace PLCG.Controllers
{
    public class TechnologyController : Controller
    {
        private EFDbContext _efDbContext = new EFDbContext();

        #region Select

        public ActionResult Index()
        {
            return View(_efDbContext.Technologies);
        }
        #endregion

        #region Delete

        public RedirectToRouteResult Delete(Technology technology, string returnUrl)
        {
            Technology tech = _efDbContext.Technologies.FirstOrDefault(t => t.TechnologyID == technology.TechnologyID);

            if (tech != null)
            {
                _efDbContext.Technologies.Remove(tech);
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Create

        public ViewResult Create()
        {
            return View(new Technology());
        }

        [HttpPost]
        public ActionResult Create(Technology technology, string returnUrl)
        {
            Technology tech = new Technology
            {
                TechnologyName = technology.TechnologyName,
                TechnologyType = technology.TechnologyType
            };

            _efDbContext.Technologies.Add(tech);
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion

        #region Update

        public ActionResult Update()
        {
            return View(new Technology());
        }

        public ActionResult Update(Technology technology, string returnUrl)
        {
            Technology tech = _efDbContext.Technologies.FirstOrDefault(t => t.TechnologyID == technology.TechnologyID);

            if (tech != null)
            {
                tech.TechnologyName = technology.TechnologyName;
                technology.TechnologyType = technology.TechnologyType;
            }
            _efDbContext.SaveChanges();
            return RedirectToAction("Index", new { returnUrl });
        }

        #endregion
    }
}

PLCG/Views/Shared/_AdminLayout.cshtml
@{Layout = null;}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    @Html.ActionLink("Companies", "Index", "Company", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Locations", "Index", "Location", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Technologies", "Index", "Technology", null, new { @class = "btn btn-default" })
                    <div>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

PLCG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"7a437dd0-253f-4bc5-935c-6e28e0d06fd1"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>